import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Common/NavBar";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from '@clerk/nextjs'
import Hero from "@/components/Landing/Hero";
import Footer from "@/components/Landing/Footer";
import {dark} from "@clerk/themes"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        // variables: {
        //   colorPrimary: "#a21caf", // purple
        //   colorBackground: "#18181b", // dark background
        //   colorText: "#fff", // white text
        //   colorInputBackground: "#27272a",
        //   colorInputText: "#fff",
        // },
        elements: {
          card: "rounded-2xl shadow-lg",
        },
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SignedOut>
            <Hero/>
            <Footer/>
          </SignedOut>
          <SignedIn>
            <NavBar />
            {children}
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
